# Exercise 1B - Sourcing rainfall and flow data {-}

## Introduction {#E1B_1 -}

The previous exercise focussed on estimating rainfall and runoff at catchment scales during a storm event.  This focussed on catchment scale rainfall and processes.  In this exercise we will examine the nature of rainfall data and use some simple statistics to describe these data.  We then look at how rainfall may be changing over time and how it varies over space across Western Australia.  After that we explore how different modes of climate variability affect annual rainfall.  Lastly, we look at the relationships between rainfall and runoff.  To achieve this, we use a large number of weather stations across WA to quantify the variability of rainfall in space and time.


## Objectives {#E1B_2 -}

By the end of this activity, you should:

1) Be able to source rainfall and flow data, understand the nature of that data and describe it using simple statistics in Excel.

## Statistical Properties of Rainfall Data {#E1B_3 -}

**Download the answer sheet for this exercise by clicking the download button in the tool bar** <i class="fa fa-download" aria-hidden="true"></i>. 

1) Individually (make sure you have at least one person per station but you can have more than one if needed). Start by downloading the daily rainfall data for your site from the [Bureau of Meteorology](http://www.bom.gov.au/climate/data/) web site.  Use the site ID to get the data as below. Download and extract the zipped file to get a CSV file that can be opened in Excel.

<center>
<video width="100%" height="100%" controls>
  <source src="images/exercise1A/video1.mp4" type="video/mp4">
</video>
</center>

2) First, let’s plot the time series of DAILY rainfall. Clean up the plot as required and submit on your answer sheet. Describe the main features of this data set. What is the most appropriate type of graph for rainfall data?

3) Calculate the annual SUM of rainfall. We want to ensure that there are only whole years to calculate the sums or else they will be in error. Delete the rows of data for the last partial year (2019) and any partial years at the start. Select the required data across multiple columns (year C to rainfall amount F). Then insert PIVOT table (Create a new tab). Select Year and Rainfall amount as the FIELDS. Drag the Year FIELD into the ROWS box. Left click on the “Sum of Year” in the VALUES box and remove it. Plot the annual sums as a timeseries. Clean up the plot as required and submit on your answer sheet. What are the main features of this annual data set? What variability can you see? 


4) Use the Data Analysis add-in to calculate descriptive statistics (mean annual rainfall, max annual rainfall, min annual rainfall, Standard deviation of annual rainfall, Skewness) for the whole data (you can install by going to *Tools->Add-ins->Analysis ToolPack*).
Copy the results [here](https://docs.google.com/spreadsheets/d/1gFbXF9USMM8nQghy1P0cIThnNT3TFadwFy2RstU41PA/edit?usp=sharing) and complete Table \@ref(tab:table4) for your site (and others when they are done). Describe the values you got and what they mean. How “useful” are these statistics for your understanding of the system? What if any assumptions are there about these statistics? 

<!-- Old link: -->
<!-- https://docs.google.com/spreadsheets/d/10mHrNWEHoqWif96e7SwvowfQ7sMg_qMxFtw6POr7sG4/edit?usp=sharing -->

5) Next, let’s look at the distribution of the rainfall data. Do this by plotting a histogram of the rainfall data (you will need to decide on a reasonable bin size) and plotting the cumulative probability distribution (you can ask Excel to generate this automatically when it makes the histogram, or generate it manually – each data point represents a probability of 1/#data points). What do these plots tell you about the rainfall data? Are the data normally distributed? 

6) Plot the seasonal (monthly average) rainfall. Use a PIVOT table again. Insert PIVOT table (select OK to create a new tab). Select **Month** and **Rainfall** amount as the FIELDS; drag the Month FIELD into the ROWS box. Left click on the “Sum of Month” in the VALUES box and remove it. Plot the annual sums as a timeseries. Clean up the plot as required and submit on your answer sheet.
How would you describe the seasonal pattern of rainfall (hint look at the climate type)? What factors may influence it (hint, think about earth orbit)? 

<center>
```{r table4, echo=FALSE, message=FALSE, warning=FALSE}
library(knitr)
library(kableExtra)
options(kableExtra.html.bsTable = F, knitr.kable.NA = '')
table4 <- read.csv("tables/exercise1A/table4.csv", check.names=FALSE)
kable(table4,"html", escape = F, align = rep('c', 5), caption = "Bureau of Meteorology Automatic Weather Station data and station ID across WA and SWWA. Complete the table for each site [here](https://docs.google.com/spreadsheets/d/1gFbXF9USMM8nQghy1P0cIThnNT3TFadwFy2RstU41PA/edit?usp=sharing).",
      bootstrap_options = "hover") %>%
  kable_styling(table1, bootstrap_options = "hover", "striped",
                full_width = F, position = "center",
                font_size = 12) %>%
  column_spec(1, width_min = "10em") %>%
  column_spec(2, width_min = "10em") %>%
  column_spec(3, width_min = "10em") %>%
  column_spec(4, width_min = "10em") %>%
  column_spec(5, width_min = "10em") %>%
  column_spec(6, width_min = "10em") %>%
  row_spec(1:25, background = 'white') %>%
  scroll_box(width = "100%", height = "515px",
             fixed_thead = FALSE)
```
</center>
